name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - uses: ramsey/composer-install@v2
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.COMPOSER_AUTH }}"} }'

      - name: Install Yarn dependencies
        run: sudo yarn --frozen-lockfile

      - name: Prepare Application
        run: cp .env.example .env && php artisan key:generate

      - name: Clear Config
        run: php artisan config:clear && php artisan route:clear

      - name: Run Tests
        run: ./vendor/bin/pest --coverage --min=100 --coverage-html=.coverage --coverage-clover=coverage.xml tests/

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
